### ISSUE TITLE
Burger icon not hidden when menu is opened

### ISSUE THREAD

**Issue by jsArgus** [offirgolan/ember-burger-menu#3]
Unlike the demo page the burger icon isn't hidden when the menu is opened (the <a> tag doesn't get a `burger-hidden` class). Is this added as a custom feature on the demo page? If so could this be added as an option?

**Comment by offirgolan** [comment]
Hi there @jsArgus! 

This addon doesnt actually handle how you you show / hide your menu icon. That is totally up to you but it does provide you all the information you need. Feel free to checkout the demo code to see exactly how it was done. 

Below is the handlebars code used:

```hbs
    <a class="hamburger {{burger.state.position}} {{if burger.state.open 'burger-hidden'}}" {{action burger.state.actions.toggle}}>
      <i class="fa fa-bars" aria-hidden="true"></i>
    </a>
```

And this is the SASS:

```css
.hamburger {
  opacity: 1;
  transition: opacity 0.3s;
  -webkit-transition: opacity 0.3s;

  &.burger-hidden {
    opacity: 0;
  }
}
```

Pretty simple 😄
